src/apps/api_tvempresa/urls.py
from django.urls import path
from django.conf.urls import url


from rest_framework import routers
from .viewsets import CapitulosViewSet, ProgramasViewSet, SearchCapituloList, HomeViewSet
app_name = 'api_tvempresa'

router = routers.SimpleRouter()
router.register('api_capitulos_tvempresa', CapitulosViewSet)
router.register('api_programas_tvempresa', ProgramasViewSet)
router.register('api_search_capitulos', SearchCapituloList)
router.register('api_home_video', HomeViewSet)

urlpatterns = router.urls

src/apps/core/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [

    url(r'^utils/',
        include([
            url(r'^status-task/$',
                views.StatusTaskAPIView.as_view(),
                name="status-task"),
        ])),

]

urlpatterns = format_suffix_patterns(urlpatterns)

src/apps/web/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (home, capitulo_detalle, buscador, app, app_ios, politicas)

from .api import CapitulosList, CapitulosDetail

app_name = 'web'

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^capitulo/(?P<slug>[-\w]+)/$', capitulo_detalle, name='capitulo_detalle'),
	url(r'^buscador/', buscador, name='buscador'),
	url(r'^app/', app, name='app'),
	url(r'^app-ios/', app_ios, name='app_ios'),
	url(r'^politicas/', politicas, name='politicas'),
	
]

src/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.web.urls')),
    path('api/v1.0/', include('apps.api_tvempresa.urls')),

    ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

src/apps/core/models.py
# -*- coding: utf-8 -*-

from django.db import models
from .managers import ActiveInactiveManager


class AuditableModel(models.Model):
    active = models.BooleanField('Activo', default=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)
    modified = models.DateTimeField(editable=False, auto_now=True)
    created_by = models.IntegerField('Creado por', editable=False, null=True,
                                     default=0)
    modified_by = models.IntegerField('Modificado por', editable=False,
                                      null=True, default=0)

    objects = ActiveInactiveManager()

    class Meta:
        abstract = True


class SlugModel(models.Model):
    nombre = models.CharField('Nombre', max_length=120)
    slug = models.SlugField('slug', max_length=180, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.nombre


class PositionModel(models.Model):
    position = models.SmallIntegerField('Posición', default=0)

    class Meta:
        abstract = True
        ordering = ['position']

src/apps/web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Principal(models.Model):
	nombre_video_principal = models.CharField('Nombre Video Principal', max_length=200, blank=True, null=True)
	video_principal = models.URLField('Video Principal', blank=True, null=True)
	videos_activo = models.BooleanField('Video Activo', default=True)
	order_video = models.IntegerField('Orden del Videos', blank=True, null=True, unique=True)
	def __str__(self):
		return self.nombre_video_principal
		
	class Meta:
		verbose_name = "Video Principal"
		verbose_name_plural = "Videos Principales"
		ordering = ['order_video']

class Productora(models.Model):
	nombre_productora = models.CharField('Nombre Productora', max_length=200)
	imagen_productora = models.ImageField('Imagen Productora', max_length=200, upload_to='productoras/', help_text="Tamaño 664x362", blank=True, null=True)

	def __str__(self):
		return self.nombre_productora


class Programa(models.Model):
	usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
	nombre = models.CharField('Nombre', max_length=200)
	orden_programa = models.IntegerField('Orden Programa', blank=True, null=True, unique=True)
	imagen_programa = models.ImageField('Imagen Programa', max_length=200, upload_to='programas/', help_text="Tamaño 664x362", blank=True, null=True)
	active = models.BooleanField('Active', default=True)
	productora = models.ForeignKey(Productora, blank=True, null=True, on_delete=models.CASCADE)
	 

	class Meta:
		verbose_name = "Programa"
		verbose_name_plural = "Programas"
		ordering = ['orden_programa']

	def __str__(self):
		return self.nombre

	


class Capitulos(models.Model):
	programa = models.ForeignKey(Programa, related_name='programa', on_delete=models.CASCADE)
	numero_capitulo = models.IntegerField('Numero')
	fecha_emision = models.DateTimeField('Fecha de emision')
	titulo = models.TextField('Titulo', max_length=70, blank=True, null=True)
	descripcion = models.TextField('Descripcion', blank=True, null=True)
	imagen_principal = models.ImageField('Imagen Principal', max_length=200, upload_to='capitulos/', help_text="Tamaño 664x362", blank=True, null=True)
	video = models.URLField('Video url', blank=True, null=True)
	slug = models.SlugField(max_length=2000, blank=True, null=True)
	tags = TaggableManager(blank=True)
	logo_titulo = models.ImageField('Logo Titulo', upload_to='logos_titulos/', blank=True, null=True)
	nombre_productora_por_capitulo = models.CharField('Nombre Productora por Capitulo', max_length=200, blank=True, null=True)
	mostrar_principal = models.BooleanField('Mostrar en principal', default=True)
	

	class Meta:
		verbose_name = "Capitulo"
		verbose_name_plural = "Capitulos"
		ordering = ['-numero_capitulo']

	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		return reverse('web:capitulo_detalle', kwargs={'slug': self.slug})




		

src/apps/web/views.py
import json
from django.shortcuts import render
from django.http.response import JsonResponse, HttpResponse
from apps.web.models import (Programa, Capitulos, Productora, Principal)


def home(request):
    tipo_pagina = 'web'
    programas = Programa.objects.all()
    video = Principal.objects.all().order_by('order_video')
    for programa in programas:
        capitulos = programa.programa.all
        print("titulo", capitulos)
            
    return render(request, "index.html", locals())


def capitulo_detalle(request, slug):
    capitulo_detallado = Capitulos.objects.select_related("programa").get(slug=slug)
    
    programa = Programa.objects.get(nombre=capitulo_detallado.programa)
    capitulos = programa.programa.all()
    programas = Programa.objects.all()
    urls = Capitulos.objects.filter(slug=slug)
    return render(request, 'capitulo_template.html', locals())



def buscador(request):
    if request.is_ajax() and request.method == 'POST':
        data = json.loads(request.read().decode('utf-8'))
        titulo = data['busqueda']
        
        if titulo:
            capitulos = Capitulos.objects.filter(titulo__icontains=titulo)
            print('capitulos', capitulos)
            items_list = []
            for item in capitulos:
                titulo = item.titulo
                image_url = item.imagen_principal.url
                numero_capitulo = item.numero_capitulo
                slug = item.slug
                capitulo = {'titulo': titulo, 'image_url': image_url, 'numero_capitulo': numero_capitulo, 'slug': slug}
                items_list.append(capitulo)
                print('items_list', items_list)
        return JsonResponse({'items_list': items_list})

def app(request):
    response = HttpResponse("", status=302)
    response['Location'] = "https://play.google.com/store/apps/details?id=com.teveempresa.harolcalzada"
    return response


def app_ios(request):
    response = HttpResponse("", status=302)
    response['Location'] = "https://apps.apple.com/pe/app/teve-empresa/id1523399809"
    return response

def politicas(request):
    return render(request, 'politicas.html')

src/apps/web/templates/capitulo_template.html
{% extends "web/base.html" %}
{% load static %}
{% block social_facebook %}
  <meta property="og:url"           content="{{request.build_absolute_uri}}" />
  <meta property="og:type"          content="article" />
  <meta property="og:title"         content="{{capitulo_detallado.titulo}}" />
  <meta property="og:description"   content="{{capitulo_detallado.descripcion}}" />
  <meta property="og:image"         content="http://tevempresa.com{{capitulo_detallado.imagen_principal.url}}" />
  <meta property="og:image:width"   content="300"/>
  <meta property="og:image:height"   content="300" />

{% endblock social_facebook %}

{% block css %}
    <style type="text/css">
        img.imagen-back-movie {
          width: 100%;
          height: 750px;
        }
        section.movie-descripccion {
          margin-top: 5%;
        }
        span {
          font-size: 100px;
          color: white !important;
        }
        button.owl-prev {
          position: absolute;
          top: 15%;
          left: 0%;
        }
        button.owl-next {
          position: absolute;
          top: 15%;
          left: 98%;
        }

        .owl-theme .owl-nav [class*=owl-]:hover {
              background: none;
              color: #FFF;
              text-decoration: none;
        }
        video#my_video {
          width: 100%;
        }

        html {
          background: black;
        }

        nav {
            background-color: rgba(0, 0, 0, 0);
            box-shadow: none;
        }
        .brand-logo{
            left: 2rem;
        }

        .sidenav-color li a:hover:not(.login){
            color:#4dd0e1;
        }

        h4 {
            text-align: center;
            color: white;
            font-size: 20px;
            padding-top: 10px;
            padding-bottom: 10px;
            text-transform: uppercase;
        }
        .icons-shared {
            display: table;
            margin: auto;
        }
        .div_icon {
            float: left;
            margin: 10px;
        }
        .icons-shared a {
            display: block;
            text-align: center;
            padding: 10px 15px;
            transition: all 0.3s ease;
            color: white;
            font-size: 20px;
            width: 100%;
        }
        a.twitter {
            background: #007bff;
        }
        a.linkedin {
            background: #007bff;
        }
    </style>
{% endblock css %}
{% block content %}
  <body>

                    <section class="movie-descripccion">
                      <div class="row container">
                          <div class="col-md-7">
                            <div class="video__index">
                            <video controls id="my_video">
                              <source src="{{capitulo_detallado.video}}" type="video/mp4">
                            </video>
                            </div>
                          </div>
                          <div class="col-md-5 description">                 
                              {% if capitulo_detallado.logo_titulo%}
                              <div class="img_productora">
                                <img class="logo__productora" src="{{capitulo_detallado.logo_titulo.url}}">
                              </div>
                              {% else %}
                              <div class="img_productora">
                                <img class="logo__productora" src="{{capitulo_detallado.programa.imagen_programa.url}}">
                              </div>
                              {% endif %}
                              <div>
                                <p class="white-text texto_fecha">
                                  {{capitulo_detallado.titulo}}
                                </p>
                                <p class="white-text">
                                  {{capitulo_detallado.descripcion}}
                                </p>
                                {% if capitulo_detallado.nombre_productora_por_capitulo %}
                                <p class="white-text">
                                  Producido por : {{capitulo_detallado.nombre_productora_por_capitulo}}
                                </p>
                                {% elif capitulo_detallado.nombre_productora_por_capitulo == None %}

                                {% else %}
                                <p class="white-text">
                                  Producido por : {{capitulo_detallado.programa.productora}}
                                </p>
                                {% endif %}
                              </div>
                              <h2 class="titulo_compartenos">Compartenos en :</h2>
                              <div class="icons-shared">
                                <div class="div_icon">
                                  <a href="http://www.facebook.com/sharer.php?u={{request.build_absolute_uri}}" target="blank" class="facebook"><i class="fa fa-facebook"></i></a> 
                                </div>
                                <div class="div_icon">
                                  <a href="#" class="instagram"><i class="fa fa-instagram"></i></a> 
                                </div>
                                <div class="div_icon">
                                  <a href="#" class="twitter"><i class="fa fa-twitter"></i></a> 
                                </div>
                                <div class="div_icon">
                                  <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                                </div>
                              </div>
                              <br>
                          </div>
                      </div>
                    </section>
                    <div class="contenedor__capitulo"> 
                      <section id="capitulo__slider">
                        <div class="row">
                          <div class="large-12 columns">
                            <h4>{{capitulo_detallado.programa}}</h4>
                            <div class="owl-carousel owl-theme">
                                
                              {% for capitulo in capitulos  %}
                              <div class="item">
                                <div class="image-content">
                                  <a href="{%url 'web:capitulo_detalle' capitulo.slug %}"><img src="{{capitulo.imagen_principal.url}}"></a>
                                </div>
                                <div class="image-caption">
                                  <h6 class="titulo-pelicula">{{capitulo.titulo|truncatechars:50}}</h6>
                                </div>
                            </div>  
                              {% endfor %}
           
                            </div>

                          </div>
                        </div>
                      </section>
                  </div>
  </body>


{% endblock content %}

src/apps/web/templates/index.html
{% extends "web/base.html" %}
{% load static %}
{% block social_facebook %}
  <meta property="og:url"           content="http://tevempresa.com" />
  <meta property="og:type"          content="article" />
  <meta property="og:title"         content="Teve Empresa" />
  <meta property="og:description"   content="El mejor canal de negocios, para las empresas." />
  <meta property="og:image"         content="http://tevempresa.com/static/img/imagen_facebook.png" />
  <meta property="og:image:width"   content="1920"/>
  <meta property="og:image:height"   content="1079" />

  <link href="http://videojs.github.io/font/css/videojs-icons.css" rel="stylesheet" />
  <link href="https://vjs.zencdn.net/5.16/video-js.min.css" rel="stylesheet" />
  <script src="https://vjs.zencdn.net/5.16/video.js"></script>
  <script src="https://cdn.rawgit.com/videojs/videojs-youtube/master/src/Youtube.js"></script>
  <script src="https://rawgit.com/atlance01/vrapp-ionic/master/www/js/lib/videojs-playlist.js"></script>
{% endblock social_facebook %}

{% block css %}
<style>


</style>
{% endblock css %}
{% block content %}


  <section id="background">

            <div class="embed-responsive embed-responsive-16by9 video-css">
              <video
                class="video-js vjs-default-skin embed-responsive-item"
                controls
                preload="auto"
                data-setup='{ "inactivityTimeout": 0 }'
                autoplay
                muted>
              </video>
            </div>

        </div>
      </div>

  </section>

  


    <!-- header -->
    <!--  Demos -->
  <div class="contenedor"> 
  {% for programa in programas %}   
    <section id="demos1">
        <div class="row" id="{{programa.nombre}}">
          
          <div class="large-12 columns">
            <h4 class="fibra">{{programa.nombre}}</h4>
          <div class="owl-carousel owl-theme">

            {% for capitulo in programa.programa.all %}
                <div class="item">
                  <div class="image-content">
                    <a href="{%url 'web:capitulo_detalle' capitulo.slug %}"><img src="{{capitulo.imagen_principal.url}}"></a>
                  </div>
                  <div class="image-caption">
                    <h6 class="titulo-pelicula">{{capitulo.titulo}}</h6>
                  </div>
              </div>    
            {% endfor %}

          </div>
        </div>
      </div>
    </section>
    {% endfor %}   
  </div>
  



{% endblock content %}
{% block js %}
      <script>
        let videoList = [
        {% for video in video  %}
            {     
              sources: [
                {
                  src:
                    "{{video.video_principal}}",
                  type: "video/mp4",
                },
              ],
            },
        {% endfor %}
    
        ];
  
        let player = videojs(document.querySelector("video"), {});
        try {
          player.volume(1);
        } catch (e) {
          console.log(e);
        }
  
        player.playlist(videoList);
        player.playlist.autoadvance(0);
      </script>
{% endblock js %}

src/templates/web/footer.html
{% load static %}  
    <footer class="footer-bs">
        <div class="row">
          <div class="col-md-4 footer-brand animated fadeInLeft">
              <img class="logo__footer" src="{% static 'img/logo.png' %}">
                <p>Producido por Blitz Communications SAC, TV Empresa es el Primer Canal de Televisión con programación especializada en Negocios, Emprendimiento e Innovación. Presenta en su programación, historias de emprendedores exitosos, programas especializados, temas de ayuda, capacitación empresarial, motivación, casos de emprendedores exitosos, gente de marketing, consejos para mejorar su negocio y mucho más.</p>
            </div>
          <div class="col-md-2 footer-nav animated fadeInUp">
              <h4>Menu —</h4>
              <div class="col-md-12">
                    <ul class="pages">
                        <li><a href="#">Programas</a></li>
                        <li><a href="#">Auspicios</a></li>
                        <li><a href="#">En vivo</a></li>
                        <li><a href="#">Contáctenos</a></li>
                        <li><a href="{% url 'web:politicas' %}">Políticas</a></li>

                      
                    </ul>
                </div>
            </div>
          <div class="col-md-2 footer-social animated fadeInDown">
              <h4>Siguenos en —</h4>
              <ul>
                  <li><a href="#">Facebook</a></li>
                  <li><a href="#">Twitter</a></li>
                  <li><a href="#">Instagram</a></li>
                </ul>
            </div>
          <div class="col-md-4 footer-ns animated fadeInRight">
              <h4>Suscríbete</h4>
                <p>Recibe todas las alertas de los nuevos contenidos que tengamos</p>
                <p>
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Ingresa tu correo">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-envelope"></span></button>
                      </span>
                    </div><!-- /input-group -->
                 </p>
            </div>
        </div>
    </footer>

src/templates/web/header.html
{% load static %}
        <!-- nav Structure -->
            <nav class="navbar navbar-expand-lg navbar-light">
              <a href="{% url 'web:home' %}" class="navbar-brand"><img class="logo" src="{% static 'img/logo.png' %}"></a>
              <button class="navbar-toggler burger" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="#">AUSPICIOS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">EN VIVO</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      PROGRAMAS
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% for programa in programas  %}
                        <a class="dropdown-item" href="http://tevempresa.com/#{{programa.nombre}}">{{programa.nombre|upper}}</a>
                      {% endfor %}
                    </div>
                  </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" id="titulo" value="" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="button" data-toggle="modal"  data-target="#exampleModal">Search</button>
                </form>
              </div>
            </nav>
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Buscador</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body ">
                      <div class="row ajax">
                      </div>
                    </div>
                  </div>
                </div>
              </div>

{% block css %}
<style type="text/css">
  .modal-dialog {
    max-width: 100%;
    height: 100%;
    margin: 0%;
  }
  .modal-content {
      height: 100%;
      background-color: #000000d9;
  }
  div#exampleModal {
    padding: 0px!important;
  }
  .modal-header {
    color: white;
    border: none;
}
</style>
  
{% endblock css %}

{% block js %}
  <script type="text/javascript">
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) == (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
              return cookieValue;
  }


  $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
              // Only send the token to relative URLs i.e. locally.
              xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
          }
      }
  });

            $('.btn-outline-success').on('click', function(e){
              e.preventDefault();
              busqueda = $('#titulo').val()
              console.log('busqueda', busqueda)
              data = {'busqueda': busqueda }
                    $.ajax({
                            url: '{% url 'web:buscador' %}',
                            type: 'POST',
                            dataType: 'json',
                            contentType: 'application/json',
                            data: JSON.stringify(data),
                        success: function(data) {
                        html_result = ''
                        $.each(data['items_list'], function(index, val) {
                          console.log('val', val['titulo'])
                        if (val['titulo']) {
                            html_result +='<div class="col-2"><div class=""><div class=""><a href="capitulo/'+val['slug']+'"><img src="'+val['image_url']+'"></a></div><div class=""><h6 class="">capitulo '+val['numero_capitulo']+'</h6></div></div></div>'
                          }
                        else {
                          html_result += ''
                        }
                      });
                      $('.ajax').html(html_result)     
                    }
              });
            });

      $('#myModal').on('shown.bs.modal', function () {
      $('#myInput').trigger('focus')
        });
  </script>
  
{% endblock js %}

src/templates/web/sss.html
{% load static %}
    <header class="header">
        <!-- nav Structure -->
        <div class="navbar-fixed">
            <nav>
                <div class="nav-wrapper">
                    <a href="{% url 'web:home' %}" class="brand-logo"><img class="logo" src="{% static 'img/logo.png' %}"></a>
                    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down sidenav-color">
                              <!-- Dropdown Trigger -->
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">PROGRAMAS<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a href="movies.html">AUSPICIOS</a></li>
                        <li><a href="series.html">EN VIVO</a></li>
                        <li><a href="prices.html">CONTÁCTENOS</a></li>
                        <li>
                            <form>
                                <div class="input-field">
                                <input id="search" type="search" required>
                                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                                <i class="material-icons">close</i>
                                </div>
                            </form>  
                        </li>
                    </ul>
                </div>
            </nav>

        </div>
        <!-- Responsive sidenav Structure -->
        <ul class="sidenav sidenav-color" id="mobile-demo">
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">PROGRAMAS<i class="material-icons right">arrow_drop_down</i></a></li>
              <li><a href="movies.html">AUSPICIOS</a></li>
              <li><a href="series.html">EN VIVO</a></li>
              <li><a href="prices.html">CONTÁCTENOS</a></li>
            <nav>
                <div class="nav-wrapper">
                    <form>
                    <div class="input-field">
                        <input id="search" type="search" required>
                        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                        <i class="material-icons">close</i>
                    </div>
                    </form>
                </div>
            </nav>
        </ul>


        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a href="{% url 'web:home' %}" class="brand-logo"><img class="logo" src="{% static 'img/logo.png' %}"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
    </header>

    <script type="text/javascript">
    $(".dropdown-trigger").dropdown();
    </script>